### ISSUE TITLE
Nullable OrderedCollectionChangeSet

### ISSUE THREAD

**Issue by shynline** [Zhuinden/realm-monarchy#13]
hi
how does the NonNull `getOrderedCollectionChangeSet()` return a Nullable `OrderedCollectionChangeSet` ?

I've read it in the official realm document about `OrderedCollectionChangeSet` 

> `null`  means the async query returns the first time.

**Comment by Zhuinden** [comment]
That changed with Realm 5.0.0 and it previously used to return `null` instead of `changeSet.getState() == INITIAL`.

So if you're using latest version of Realm, that's nonnull. 

See https://github.com/Zhuinden/realm-monarchy/blob/831ab834ed304385143f0918d7694abc42421c7a/monarchy-example/src/main/java/com/zhuinden/monarchyexample/features/managed/MonarchyDiffResult.java#L23

**Comment by shynline** [comment]
oh ok then 
I was wondering why it's working.
thanks
