### ISSUE TITLE
Cannot query synced realm using PagedLiveResults

### ISSUE THREAD

**Issue by squirtle1990** [Zhuinden/realm-monarchy#18]
I am having troubles querying a Realm Cloud instance from Monarchy.

Here are my steps to reproduce:

I call Monarchy.init in my application class

SplashActivity logs into realm using JWT authentication

Logged in Realm user creates a configuration to the realms:// endpoint

Monarchy.setDefaultConfigration(config) // on the above config

Query classes, but receive logcat error: "Schema mismatch: realms://<url>/default]: BAD_CHANGESET_DOWNLOAD(112)"

I have cleared the realm-object-server cache on all devices, server and client before testing

**Comment by Zhuinden** [comment]
Bad change set? That's unexpected...

Technically the one thing I kinda was expecting was [that `PagedLiveResults` uses `findAll()`](https://github.com/Zhuinden/realm-monarchy/blob/cda77785b4d8ca8f13f3ccf5bdaf12bc93c10619/monarchy/src/main/java/com/zhuinden/monarchy/PagedLiveResults.java#L43), but according to Realm, [`findAll()` doesn't create a subscription for some unknown reason](https://github.com/realm/realm-java/issues/5938#issuecomment-387780975) (even though it would work just fine on a background looper thread if it did).

However `bad change set` sounds like a completely different problem; possibly even version mismatch on Sync.

Maybe I really should swap the dependencies out to `provided`.

---------------------

Does the query work without Monarchy?

You supposedly get `bad change set` if you do destructive schema changes, like an Index is added/removed, PrimaryKey is added/removed, Field is made Nullable/not-nullable.

**Comment by squirtle1990** [comment]
You are correct, the bad change set issue was an unrelated issue between the client/server schema.

I do, however, have issues subscribing and updating the data from the PageLiveResults interface.

I have my realm configured as a reference Realm, so only queried data should be synced with the device. It seems when starting from a blank slate, Monarchy does not populate a recyclerview with items.

Only after creating a separate subscription with the Realm-java using findAllAsync can Monarchy populate the RecyclerView.

It also sees list items are not updated with dataset changes. This seems to be a known issue [here](https://github.com/realm/realm-java/issues/5938#issuecomment-387780975) Only after scrolling the item off screen and out of cache does onBindViewHolder get called. 

It sounds like you are acutely aware of these issues by your comment about the lack of subscription in findAll. Is this an issue that Realm-java core needs to fix?

**Comment by Zhuinden** [comment]
> however, have issues subscribing and updating the data from the PageLiveResults interface.

I'm not that surprised after having read that `findAll()` "doesn't create a subscription". Which makes sense on the UI thread, but it sure doesn't make sense on a background looper thread. You'd think just adding a change listener would enable it to create a subscription nonetheless.

Honestly, I'm not really sure what a `SyncSubscription` ***is***, I somewhat make glances at Realm Sync but as I have not used it, I cannot really verify behavior against SyncConfiguration or not. I just knew it'd eventually come back to haunt me.

The tricky thing is that I initially tried to use `findAllAsync()` as basis for Paging lib but it wasn't really working, so I tried `findAllAsync() + load()` but that didn't work either. In retrospect, I could try `findAllAsync() + refresh()` but I definitely wouldn't make that the default behavior because it seems unstable.

I especially don't know how Sync realms handle `refresh()` nor the nuances in behavior difference regarding `fullSynchronization()` and `partialRealm()` (query based) Realms. 

---------------

So if your data set isn't *that* big (especially with partial / query-based sync Realm), then you could try using `copied` or `mapped` instead of `paged` for now.

----------

However as you are using Sync, you could verify for me whether you'd need an api to `forceOpen()` the Realm on the Monarchy thread. Namely so that your session doesn't get terminated when you don't have active observers on your LiveData.

I also wonder if you'd need to run `SyncSession.downloadAllRemoteChanges()` on the Monarchy thread.

**Comment by squirtle1990** [comment]
I tried calling downloadAllRemoteChanges() from the fragment right after the creation of the paged adapter.
```
val session = SyncManager.getSession(config)
session.downloadAllServerChanges()
```
But it throws an IllegalStateException:

> No SyncSession found using the path : /data/data/package-name/files/realm-object-server/JnIoGn1667ej42FYPuMwiwKrGXs1/realm-name/realm-name
> please ensure to call this method after you've open the Realm

It appears a SyncSession isn't being created, or it is dying immediately, like you suggested.

I'm not sure what you mean by forceOpen() the Realm on the Monarchy thread? How would one write this in code?

I've had to modify the data classes I store on Realm Cloud to have Realm + object name, because in your Paging example, you mapped objects in the realmDataSourceFactory from RealmObject to Android Architecture Component friendly abstract classes with AutoValue fields. My viewholders all bind to the abstract classes, it would involve some busy work to switch to a copied or mapped query in the meantime. I'd rather help fix the paging library in the meantime.

Are you a software engineer for Realm.io? It seems there are still some behavioral changes that could be changed in Realm-java that would help the Realm work with the Paging library.

Realm current supports [Realm-Android-Adapters](https://github.com/realm/realm-android-adapters) which works well, save for the Paging functionality that Monarchy provides. Maybe Realm would want to allocate some programmers to bridge the gap?

**Comment by Zhuinden** [comment]
> I'm not sure what you mean by forceOpen() the Realm on the Monarchy thread? How would one write this in code?

This means that on my side I would expose a `monarchy.forceOpen()` (and `closeIfForcedOpen()` or something) methods where the Monarchy thread's Realm instance is kept alive as long as `closeIfForcedOpen()` is not called.

Current behavior is that the Monarchy thread is killed (and later recreated) if there are no active LiveData, but technically "activeness" of LiveData depends on both whether it is observed and the lifecycle of its LifecycleOwner. Therefore LiveData in stopped activities counts as "inactive", but Realm Sync ***demands*** for the connection to stay alive in order to synchronize between ROS and client.

I think Realm-Java uses immediate sync session stop policy, but I'm actually not sure if that is true. Which means if Realm is not open on any threads, then Realm Sync Session is terminated, which is bad for Sync + Sync's listeners + stuff.

Another question is that you probably would want to... hold on a sec, I think `waitForInitialRemoteData()` on SyncConfiguration would work in place of using `SyncSession.downloadAllServerChanges()`. Yay?

Either way, I never added `forceOpen()` because I had the idea that it *might* be needed for Sync, but I wasn't sure? As I said, I don't use Sync.

> Realm current supports Realm-Android-Adapters which works well, save for the Paging functionality that Monarchy provides. Maybe Realm would want to allocate some programmers to bridge the gap?

Realm-Android-Adapters reads the data from file on the thread where it is accessed which is the UI thread, unless you do the trickery that Monarchy does internally. This is the *reason* why Monarchy exists.

> Are you a software engineer for Realm.io?

No, I just answer DB related questions :smile: 

> My viewholders all bind to the abstract classes, it would involve some busy work to switch to mapped query

Depending on how much you are using `PagedListAdapter` and stuff, although I guess I see what you mean. I assumed moving to `findAllMappedWithChanges` should be fairly simple, but I guess not.

------------

------------

The problem is that I'm not sure what I need to change on my side to make Paging work with Sync, other than that you *somehow* need to use `findAllAsync` in a paged live results.

I could add an experimental version that uses that, but I can't guarantee that it works. That is why I used `findAll()` in the first place.

Technically what I could do is say that if the result set says `!isLoaded()` then just return `0` size, maybe that'd help.. I'll add an `asAsync` version for `PagedLiveResults` tomorrow and hope for the best.

**Comment by squirtle1990** [comment]
I tried one more thing...
Since your library uses Realm v5.1, and I was using v5.5, I downgraded and gave it a try.
I also called waitForInitialRemoteData.
Quite a few things have changed between those versions for logging into a synced realm.
`val config = SyncConfiguration.Builder(SyncUser.current(), getString(R.string.REALM_SYNC_URL)).partialRealm().waitForInitialRemoteData().build()`

The result is the same, a new partial realm is created in Realm Studio, but it is empty, with the same schema as the reference realm.

No objects are synced with the client :/

In the meantime, I changed to findAllMappedWithChanges and changed my adapter from a PagedListAdapter to a ListAdapter and Realm objects sync to the list, just not paginated :(

**Comment by squirtle1990** [comment]
This is probably a issue that should be suggested to the Realm-java team. It sounds like the solution might be on their end, and I'm sure they want their library to support paginated list loading as well.

**Comment by Zhuinden** [comment]
Technically they say "our data is lazy-loaded when accessed on the UI thread so you can use RealmResults with findAllAsync and it works", which is slightly true and `findAllManaged` would also work if run with `asAsync`.

I didn't have the time yesterday unfortunately. In fact, technically I'm just not sure how to manage the release of this beta feature.

Easiest thing would be to create a new branch with the necessary code, you could clone that branch and you could copy the code of monarchy into your project, and see if it is behaving erratically or not.

Would that be alright with you?

**Comment by squirtle1990** [comment]
I can make a branch and make the necessary changes if your schedule is full. I'll submit the changes if they behave as expected.

**Comment by Zhuinden** [comment]
I have added the necessary code and it... uh, *might* work?

Try 0.5.0 and report back.

**Comment by squirtle1990** [comment]
The 0.5.0 changes did not work. Here's the logcat:

Method processed more than once: void android.arch.lifecycle.LiveData.<clinit>()
    Method processed more than once: void android.arch.lifecycle.LiveData.<init>()
    Method processed more than once: java.lang.Object android.arch.lifecycle.LiveData.access$000(android.arch.lifecycle.LiveData)
    Method processed more than once: java.lang.Object android.arch.lifecycle.LiveData.access$100(android.arch.lifecycle.LiveData)
    Method processed more than once: java.lang.Object android.arch.lifecycle.LiveData.access$102(android.arch.lifecycle.LiveData, java.lang.Object)
    Method processed more than once: java.lang.Object android.arch.lifecycle.LiveData.access$200()

W/dex2oat: Method processed more than once: int android.arch.lifecycle.LiveData.access$300(android.arch.lifecycle.LiveData)
    Method processed more than once: int android.arch.lifecycle.LiveData.access$302(android.arch.lifecycle.LiveData, int)
    Method processed more than once: void android.arch.lifecycle.LiveData.access$400(android.arch.lifecycle.LiveData, android.arch.lifecycle.LiveData$ObserverWrapper)
    Method processed more than once: void android.arch.lifecycle.LiveData.assertMainThread(java.lang.String)
    Method processed more than once: void android.arch.lifecycle.LiveData.considerNotify(android.arch.lifecycle.LiveData$ObserverWrapper)
    Method processed more than once: void android.arch.lifecycle.LiveData.dispatchingValue(android.arch.lifecycle.LiveData$ObserverWrapper)

W/dex2oat: Method processed more than once: java.lang.Object android.arch.lifecycle.LiveData.getValue()
    Method processed more than once: int android.arch.lifecycle.LiveData.getVersion()
    Method processed more than once: boolean android.arch.lifecycle.LiveData.hasActiveObservers()
09-14 14:00:33.314 10716-10716/? W/dex2oat: Method processed more than once: boolean android.arch.lifecycle.LiveData.hasObservers()

**Comment by Zhuinden** [comment]
@ogtimothymiller did you change the `createDataSourceFactory` call to use `, true`?

**Comment by Zhuinden** [comment]
I actually don't know what this means, by the way. Try to `monarchy.openManually()` before you start observing Monarchy's LiveDatas.

**Comment by squirtle1990** [comment]
Whoops I forgot to set asAsync to true in createDataSourceFactory. With asAsync enabled, items are fetched from Realm and initially display in the RecyclerView, but shortly after, there is a crash in the areItemsTheSame method, where one of the Realm objects returns null for all nullable fields. When I override the diffUtil methods to not access object fields, the crash disappears, but the list items are blank starting around the third page of items.

openManually() is not necessary and doesn't seem to have an affect on the code behavior.

What's most strange is the RecyclerView will scroll infinitely down, but no matter how much you scroll down, you can scroll to the top of the list in one swipe.

**Comment by Zhuinden** [comment]
...now that kinda makes me remember why I was using `findAll()`, but 

>  there is a crash in the areItemsTheSame method, where one of the Realm objects returns null for a particular string field.

That is a bit more surprising than expected, I wouldn't think you can *load* the data and see it there without it being there? DiffUtil of course is on your side of things, you could potentially check for nulls.

> What's most strange is the RecyclerView will scroll infinitely down, but no matter how much you scroll down, you can scroll to the top of the list in one swipe.

This is the real bug here and I have honestly no idea what's going on, then. :/ maybe I should change it so that instead of `copyFromRealm`ing the window that I want to send out, when `findAllAsync()` finishes I copy it out right there and then, and return bits of that from the paging side of things.

The downside is that `@LinkingObjects` is always `null` in a detached object. Then again, if I let you throw in a `Mapper` instead of `copyFromRealm` for the detaching, that could work...

The problem is that the bug itself is fairly esoteric and I can't reproduce it, but this sounds like it could potentially work.

**Comment by squirtle1990** [comment]
At this point, I'm not exactly sure the what's going on with copyFromRealm and Mapper. I'm going to read through your Monarchy.java class and lookup the associated Realm documentation as I go so I can help solve this issue.

**Comment by Zhuinden** [comment]
> I should change it so that instead of copyFromRealming the window that I want to send out, when findAllAsync() finishes I copy it out right there and then, and return bits of that from the paging side of things.

This is actually a really stupid idea because that would mean I'm essentially "copying out the whole list" just to make paging work, essentially throwing away the benefits of paging.

I'm not even sure why I came up with that.

On the other hand, that means I'm not sure what to do. :cry: Paging with Sync on a background looper thread is hard!

**Comment by squirtle1990** [comment]
Just brainstorming here, what if the data frame queried from Realm was increased on every increase in page count? In pseudocode:

on next page requested -> data = query from realm (limit = pagesize * pagenumber)
notify items inserted (data)

**Comment by Zhuinden** [comment]
`notifyItem*` is calculated by AsyncPagedListDiffer, so that is not our responsibility.

As for loading more and more - the `pageSize` is provided by the LivePagedListBuilder (i think), so theoretically I shouldn't have to reload additional items on top of that.

I do not know why it resets to 0th position each time. Maybe because `getItemCount()` returns `invalid` as the results is not loaded?

**Comment by squirtle1990** [comment]
If I’m understanding correctly, you hypothesize getItemCount() returns an invalid value because of the query somewhere down the food chain is not returning the proper page of items? It’s strange how the list capped out at around the second or third page.

After looking at PagedLiveResults, I’m curious how often the query is updated over the lifecycle of the LiveData. As I understand, we cannot findAll(Async) just once like CopiedLiveResults as the amount of data we are requesting from Realm is dyanamic.

As it stands, I don’t think it’s possible to fetch paged results from Realm, we need proper support from the main branch.

**Comment by squirtle1990** [comment]
I noticed you are using PositionalDataSource to mediate data access.

I found this section on Google’s developer page:
“Extend PositionalDataSource if you can load pages of a requested size at arbitrary positions, and provide a fixed item count. If your data source can't support loading arbitrary requested page sizes (e.g. when network page size constraints are only known at runtime), use either PageKeyedDataSource or ItemKeyedDataSource instead.”

Because we cannot load arbitrary postitions, we cannot use this library yet?

**Comment by Zhuinden** [comment]
> Because we cannot load arbitrary postitions, we cannot use this library yet?

RealmResults is positional. I'm actually not entirely sure why `findAllAsync()` breaks the mechanism the more i think about it, because Room's results also are evaluated async.

Technically currently I'd expect to be able to blocking-get the items when necessary (hence the `realm.refresh()` call in `isInvalid()`) but that does not seem to work with Sync, and honestly neither did `load()`.

**Comment by squirtle1990** [comment]
This is possibly related: 
https://github.com/googlesamples/android-architecture-components/issues/307#issuecomment-401503809

**Comment by Zhuinden** [comment]
I don't think so, because RealmResults (and therefore LiveResults) is positional data source.

**Comment by squirtle1990** [comment]
I spoke with Eric from Realm Technical Support. He said paginated scrolling is a planned feature for Realm in early 2019.

> I've spoken with our product team and confirmed that pagination is on our roadmap and currently in development. Our release date for it should be sometime in early 2019.
> 
> Ticket: https://support.realm.io/helpdesk/tickets/1886

**Comment by Zhuinden** [comment]
They're working on `limit/offset` mechanism which would let you use RealmResults as a page keyed data source.

We'll cross that bridge when we get there.

In the meantime,  I have to admit that I might remove the `asAsync` from PagedLiveResults, as it clearly doesn't work correctly; and otherwise have to admit defeat regarding this. I'm not sure what to do with it for now, and I'm not sure what can make `findAllAsync` work with Paging in general.

**Comment by squirtle1990** [comment]
I'm not sure findAllAsync can work with Paging as well. It sounds like a limit/offset mechanism is exactly what we need to provide the data layer for PagedLiveResults. Why is this not the case?

**Comment by Zhuinden** [comment]
Because it doesn't solve the issue of async RealmResults being "temporarily unavailable".

Technically there is a chance that I could force the creation of a subscription for synchronous RealmResults through package-internal methods, but for that I'll *definitely* wait for Realm Core 6 and the new Realm Studio and Realm Java 6, because it seems very unlikely that it won't be changed over time.

**Comment by Zhuinden** [comment]
I wonder what would happen with LOADRESULTS=TRUE, SubscriptionAction(create). 

https://github.com/realm/realm-java/blob/e3cb81cf5707e5fc8ad1bd83729bc80f901ebde4/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L2088

But it would require reflection.

**Comment by Zhuinden** [comment]
@ogtimothymiller there is a chance that the solution will be to use the new "explicit subscribe" method that is being added to Realm, because findAllAsync won't work, but findAll with a subscription *would*.

see https://github.com/realm/realm-java/pull/6231

**Comment by cmelchior** [comment]
Just to clarify a few things:

A subscription doesn't contain any data by itself. It just wraps the "intent" of wanting to download data from the Server, but the download itself is asynchronous. Unsubscribing from it will also make the data disappear again from the device.

So manually creating the subscription in a synchronous manner would not actually download any data unless you also explicitly trigger a download as well. With the PR you referenced, it would look something like this:

```
RealmQuery<Foo> query = realm.where(Foo.class).greaterThan("id", 42);
realm.executeTransaction(r -> { query.subscribe(); });
SyncSession session = SyncManager.getSession((SyncConfiguration) realm.getConfiguration());
session.uploadAllLocalChanges(); // Upload subscriptions
session.downloadAllServerChanges(); // Download subscription data
realm.refresh(); // Required because download happen in a background thread
query.findAll(); // This should now contain the relevant data. 
```

Regarding `findAllAsync()` then that is similar to the `Network + Database` example from Googles docs: https://developer.android.com/topic/libraries/architecture/paging/#network-with-database-data-arch, but unfortunately I haven't had time to play around with it yet to provide proper guidance on how to implement it there. 

`BAD_CHANGESET_DOWNLOAD` is not all related to any of this. That indicates a problem with the Realm files on the server and/or network problems.

**Comment by Zhuinden** [comment]
PagedLiveResults has been removed in favor of FrozenLiveResults.

This is no longer applicable.

I had no idea how to solve this, but with the new sync, it's probably obsolete anyway.
